In [7]:
# the notebook requiers that 
# - a cluster has been started with
#   ipcluster start -n 4 --engines=MPIEngineSetLauncher --profile=mpi 
#   and a file NCDFParallelIOExample_original/psum.py 
#   does exist
import ipyparallel as ipp

In [8]:
 c = ipp.Client(profile='mpi')
    

In [9]:
view = c[:]


In [10]:
view.activate()

In [12]:
view.run('NCDFParallelIOExample_original/psum.py')

<AsyncResult: execute>

In [13]:
 view.scatter('a',np.arange(16,dtype='float'))

<AsyncResult: scatter>

In [14]:
view['a']


[array([0., 1., 2., 3.]),
 array([4., 5., 6., 7.]),
 array([ 8.,  9., 10., 11.]),
 array([12., 13., 14., 15.])]

In [15]:
%px totalsum = psum(a)

<AsyncResult: execute>

In [16]:
 view['totalsum']
    

[array(120.), array(120.), array(120.), array(120.)]